title = "Air Fryer Lover"
baseURL = "https://aflover.vercel.app"
languageCode = "en-us"
theme = "docsy"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
HUGO_ENV="production"
copyright = 'Â© 2024 Air Fryer Lover'

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ['html', 'rss']

[params]
  favicon = ""
  description = "For All Air Fryer Lover."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  env = "production"
  mastodon = ""
  sponser = "https://airfryerwonder.com"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 10
[menus]
  [[menus.footer]]
    name = 'Terms'
    pageRef = '/terms'
    weight = 10
  [[menus.footer]]
    name = 'Privacy'
    pageRef = '/privacy'
    weight = 20
  [[menus.main]]
    name = 'Home'
    pre = '<i class="fa fa-heart"></i>'
    url =  ''
    weight = 10
    [menus.main.params]
      rel = 'external'


